/**
 * BrushPresets — 94 curated brush presets (stamps, textures, dynamics).
 * Extracted via Frida hook on ConcealHelper.decryptByte().
 */

import type { BrushPreset } from "./BrushTypes.js";
import { DEFAULT_BRUSH } from "./BrushTypes.js";

export interface BrushPackage { name: string; brushes: BrushPreset[]; }

export const PACKAGES: BrushPackage[] = [
  { name: "常规画笔", brushes: [
      {"id": "tzBgMXfeSiKGV1aUY-fO0w", "name": "橡皮擦", "pkgName": "常规画笔", "width": 131.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 1.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 1.0, "dynamicBrushFlow": 0.0, "spacing": 0.05, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 4.4, "reverseTex": false, "reverseShape": false, "eraser": true, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 100, "blendType": 0},
      {"id": "piAkdgIST0KvHbQIqsZu1Q", "name": "软橡皮擦", "pkgName": "常规画笔", "width": 131.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 1.0, "dynamicAlpha": 0.0, "brushFlow": 0.25, "smallBrushFlow": 0.25, "dynamicBrushFlow": 0.0, "spacing": 0.05, "dynamicSpa": 0.0, "hardness": 0.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 4.4, "reverseTex": false, "reverseShape": false, "eraser": true, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 100, "blendType": 0},
      {"id": "g1SmMcEeTEOlQTTIQkZgvQ", "name": "像素橡皮擦", "pkgName": "常规画笔", "width": 30.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 1.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 1.0, "dynamicBrushFlow": 0.0, "spacing": 0.5, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": true, "pixelpen": true, "square": true, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 100, "blendType": 0},
      {"id": "EADUPQlCS2GBbrIaZc9U5A", "name": "二值橡皮擦", "pkgName": "常规画笔", "width": 10, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 1.0, "dynamicBrushFlow": 0, "spacing": 0.07999999821186066, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": true, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "32QEt7_uSUqMoDZTjjxTnA", "name": "铅笔", "pkgName": "常规画笔", "width": 20, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 100, "alpha": 0.8181818127632141, "smallAlpha": 0, "dynamicAlpha": 0, "brushFlow": 0.8199999928474426, "smallBrushFlow": 0, "dynamicBrushFlow": 0, "spacing": 0.15000000596046448, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "qianbi_tex", "texScale": 0.10000000149011612, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "l-aZZ3l8RM6e9vuR2CVoPw", "name": "柔边笔", "pkgName": "常规画笔", "width": 104, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1.0, "dynamicAlpha": 0, "brushFlow": 0.25, "smallBrushFlow": 0.25, "dynamicBrushFlow": 0, "spacing": 0.09000000357627869, "dynamicSpa": 0, "hardness": 0, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 4.400000095367432, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "q94wviccTHeFAL-9n7fzoA", "name": "圆珠笔", "pkgName": "常规画笔", "width": 10, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.12999999523162842, "dynamicBrushFlow": 0, "spacing": 0.07999999821186066, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "JPU_-5HvTE6ykkmwyv7xxA", "name": "喷笔", "pkgName": "常规画笔", "width": 147, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0, "dynamicBrushFlow": 0, "spacing": 0.30000001192092896, "dynamicSpa": 0, "hardness": 0, "roundness": 1, "rotation": 154, "dynamicRot": 90, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt13", "useTex": false, "surfaceTexture": "", "texScale": 2.069999933242798, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 25, "blendType": 0},
      {"id": "pWXPIFa2QIed62zhmXX9gQ", "name": "马克笔", "pkgName": "常规画笔", "width": 59, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.29, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.28999999165534973, "dynamicBrushFlow": 0, "spacing": 0.029999999329447746, "dynamicSpa": 0, "hardness": 1, "roundness": 0.8100000023841858, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "makebi_tex", "useTex": false, "surfaceTexture": "", "texScale": 0.10000000149011612, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 47, "blendType": 0},
      {"id": "CMg_dDQqQKys6oblUNU22A", "name": "水彩笔", "pkgName": "常规画笔", "width": 23, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1.0, "dynamicAlpha": 0, "brushFlow": 0.09000000357627869, "smallBrushFlow": 0.09000000357627869, "dynamicBrushFlow": 0, "spacing": 0.029999999329447746, "dynamicSpa": 0, "hardness": 1, "roundness": 0.8100000023841858, "rotation": 0, "dynamicRot": 180, "rotFlowFinger": false, "useShape": true, "shapeTexture": "suicai_tex", "useTex": true, "surfaceTexture": "suicai_shape", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "SN3Z_7oHTyqSunpeFDfPBQ", "name": "蜡笔", "pkgName": "常规画笔", "width": 54, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0, "dynamicBrushFlow": 0, "spacing": 0.10000000149011612, "dynamicSpa": 0, "hardness": 0.38999998569488525, "roundness": 0.6600000262260437, "rotation": 0, "dynamicRot": 63, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt13", "useTex": true, "surfaceTexture": "ps18", "texScale": 1.1299999952316284, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "8TQPXYEwR2uGszGBD928YQ", "name": "碳笔", "pkgName": "常规画笔", "width": 20, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.2, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.20000000298023224, "dynamicBrushFlow": 0, "spacing": 0.019999999552965164, "dynamicSpa": 0.1599999964237213, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 111, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt13", "useTex": true, "surfaceTexture": "ps12", "texScale": 0.20000000298023224, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "Pjcq_-RuRR-TBGca67kqtg", "name": "毛刷", "pkgName": "常规画笔", "width": 158, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.076, "dynamicAlpha": 0, "brushFlow": 0.25999999046325684, "smallBrushFlow": 0.019999999552965164, "dynamicBrushFlow": 0, "spacing": 0.03999999910593033, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "qianbi_tex", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "1oNhw_4wTjiSLwJOxwp4qA", "name": "像素笔", "pkgName": "常规画笔", "width": 23, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1.0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 1, "dynamicBrushFlow": 0, "spacing": 0.5, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": true, "square": true, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "WXD1G_w3SS6icpV1CIPLXg", "name": "钢笔", "pkgName": "常规画笔", "width": 7.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 50.0, "alpha": 1.0, "smallAlpha": 0.11, "dynamicAlpha": 0.0, "brushFlow": 0.35, "smallBrushFlow": 0.04, "dynamicBrushFlow": 0.0, "spacing": 0.03, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": true, "supportPressure": true, "pressReverse": true, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 100, "blendType": 0},
      {"id": "7DVGj6aMTwu7W5bp_lqHTA", "name": "粉笔", "pkgName": "常规画笔", "width": 35, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.4, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.4099999964237213, "dynamicBrushFlow": 0, "spacing": 0.029999999329447746, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 176, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt7", "useTex": true, "surfaceTexture": "ps18", "texScale": 3.299999952316284, "reverseTex": false, "reverseShape": true, "eraser": false, "pixelpen": false, "square": true, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 38, "blendType": 0},
      {"id": "dZgUfa1QShi82LhShHD8oA", "name": "中空笔", "pkgName": "常规画笔", "width": 30, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1.0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 1, "dynamicBrushFlow": 0, "spacing": 0.07999999821186066, "dynamicSpa": 0, "hardness": 0, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0.12999999523162842, "depth": 0, "blendType": 0},
      {"id": "0OKEXiJmR0KdWP4O3gyWWA", "name": "二值笔", "pkgName": "常规画笔", "width": 10, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 1.0, "dynamicBrushFlow": 0, "spacing": 0.07999999821186066, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
    ],
  },
  { name: "艺术画笔", brushes: [
      {"id": "_Hr7rJqGTVaPSQoZ-UCC3g", "name": "丝纱", "pkgName": "艺术画笔", "width": 80, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.36, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.36000001430511475, "dynamicBrushFlow": 0, "spacing": 0.019999999552965164, "dynamicSpa": 0, "hardness": 1, "roundness": 0.6600000262260437, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt13", "useTex": true, "surfaceTexture": "ps16", "texScale": 0.6200000047683716, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "gCPOoes8SUC8JMFETki6xQ", "name": "滚轴", "pkgName": "艺术画笔", "width": 51, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0, "dynamicBrushFlow": 0, "spacing": 0.029999999329447746, "dynamicSpa": 0, "hardness": 1, "roundness": 0.8100000023841858, "rotation": 85, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt13", "useTex": true, "surfaceTexture": "makebi_shape", "texScale": 0.699999988079071, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 15, "blendType": 0},
      {"id": "30xKaAGnQwWSrXfF1rp_Sw", "name": "中性笔", "pkgName": "艺术画笔", "width": 30, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.7, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.699999988079071, "dynamicBrushFlow": 0, "spacing": 0.07999999821186066, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt4", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0.0, "hollowVal": 0, "depth": 8, "blendType": 0},
      {"id": "pzaJDzjDRaSNc3F5jRQl1A", "name": "泥灰", "pkgName": "艺术画笔", "width": 83, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.054, "dynamicAlpha": 0, "brushFlow": 0.3700000047683716, "smallBrushFlow": 0.019999999552965164, "dynamicBrushFlow": 0, "spacing": 0.03999999910593033, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 188, "dynamicRot": 0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt12", "useTex": true, "surfaceTexture": "ps5", "texScale": 1.4500000476837158, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": true, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "g-tsliKAQz6f-ixD50Oiyg", "name": "木炭", "pkgName": "艺术画笔", "width": 100, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.53, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.5299999713897705, "dynamicBrushFlow": 0, "spacing": 0.019999999552965164, "dynamicSpa": 0.41999998688697815, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 58, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt13", "useTex": true, "surfaceTexture": "ps12", "texScale": 0.8299999833106995, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "UiYMbZ06R3OXgjHf_Fny3Q", "name": "碎石", "pkgName": "艺术画笔", "width": 126, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.9, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.8999999761581421, "dynamicBrushFlow": 0, "spacing": 0.699999988079071, "dynamicSpa": 0, "hardness": 1, "roundness": 0.8100000023841858, "rotation": 0, "dynamicRot": 109, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt2", "useTex": true, "surfaceTexture": "ps4", "texScale": 0.699999988079071, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 18, "blendType": 0},
      {"id": "WoJLDygzQbu-5k8-Z7vB5g", "name": "焦碳", "pkgName": "艺术画笔", "width": 150, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.53, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.5299999713897705, "dynamicBrushFlow": 0, "spacing": 0.46000000834465027, "dynamicSpa": 0.05000000074505806, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 111, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt1", "useTex": true, "surfaceTexture": "ps2", "texScale": 0.8299999833106995, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "1XjGADCkT52tF9ffzucP2g", "name": "破败石灰", "pkgName": "艺术画笔", "width": 150, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.7, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.699999988079071, "dynamicBrushFlow": 0, "spacing": 0.07999999821186066, "dynamicSpa": 0.41999998688697815, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 138, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt14", "useTex": true, "surfaceTexture": "ps8", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "Y7FKSkp5T-KClyGHwlYPcw", "name": "木炭块", "pkgName": "艺术画笔", "width": 86, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0, "dynamicBrushFlow": 0, "spacing": 0.46000000834465027, "dynamicSpa": 0.23000000417232513, "hardness": 1, "roundness": 0.8100000023841858, "rotation": 85, "dynamicRot": 142, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt18", "useTex": true, "surfaceTexture": "ps10", "texScale": 0.699999988079071, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 47, "blendType": 0},
      {"id": "t2tHwucKRqGPAzDqkE8rpQ", "name": "渲染", "pkgName": "艺术画笔", "width": 104, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.25, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.25, "dynamicBrushFlow": 0, "spacing": 0.41999998688697815, "dynamicSpa": 0.23000000417232513, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 144, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt2", "useTex": true, "surfaceTexture": "ps9", "texScale": 2.359999895095825, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 47, "blendType": 0},
      {"id": "0uAlio-WSSi08ghM5Jd1Iw", "name": "废土", "pkgName": "艺术画笔", "width": 93, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.09, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.09000000357627869, "dynamicBrushFlow": 0, "spacing": 0.3700000047683716, "dynamicSpa": 0.03999999910593033, "hardness": 1, "roundness": 0.8100000023841858, "rotation": 72, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt19", "useTex": true, "surfaceTexture": "ps19", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 60, "blendType": 0},
      {"id": "_n0EO0zkSqKvjfRxfQw5Mw", "name": "散布", "pkgName": "艺术画笔", "width": 93, "smallWidth": 1.0, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1.0, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 1, "dynamicBrushFlow": 0, "spacing": 0.03999999910593033, "dynamicSpa": 1.6100000143051147, "hardness": 1, "roundness": 1, "rotation": 58, "dynamicRot": 166, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt6", "useTex": true, "surfaceTexture": "ps19", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": true, "square": true, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0, "depth": 41, "blendType": 0},
      {"id": "nuD7g81qTOSW95E4tw9VFg", "name": "烧焦木炭", "pkgName": "艺术画笔", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.79999995, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.12, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt60", "useTex": true, "surfaceTexture": "ps10", "texScale": 2, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 3, "blendType": 0},
      {"id": "fSw2FDpQTe6d3T-flkKGsQ", "name": "沙砾", "pkgName": "艺术画笔", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.59999996, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 0.5, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt49", "useTex": true, "surfaceTexture": "ps18", "texScale": 0.59999996, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "fiIPJcNRSVGKRer_Ejs9HA", "name": "木屑", "pkgName": "艺术画笔", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 0.29999998, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt48", "useTex": true, "surfaceTexture": "ps28", "texScale": 1, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 20, "blendType": 0},
      {"id": "yyxKezBySyK0sDaz0TTgxg", "name": "软纸", "pkgName": "艺术画笔", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0.01, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt64", "useTex": true, "surfaceTexture": "ps36", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
    ],
  },
  { name: "勾线画笔", brushes: [
      {"id": "gholuZ5mQCSzGB-BniYyzw", "name": "传统铅笔", "pkgName": "勾线画笔", "width": 15.2, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.099999994, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 180.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt15", "useTex": true, "surfaceTexture": "ps29", "texScale": 0.29999998, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 50, "blendType": 0},
      {"id": "XJndlqBiRBmN4ZI-OktG3g", "name": "粗糙铅笔", "pkgName": "勾线画笔", "width": 13.8, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.39999998, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 72.0, "dynamicRot": 180.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt16", "useTex": true, "surfaceTexture": "ps24", "texScale": 1.1899999, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "Mq5Jhg8EQhatJ901jM6VeQ", "name": "碳铅笔", "pkgName": "勾线画笔", "width": 20.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.59999996, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.06, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 255.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt15", "useTex": true, "surfaceTexture": "ps24", "texScale": 0.29999998, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 27, "blendType": 0},
      {"id": "OrHzVkReQy-II3lSf7rrqg", "name": "美术笔", "pkgName": "勾线画笔", "width": 20.0, "smallWidth": 1.0, "dynamicWidth": 0.5, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.099999994, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.04, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 237.0, "dynamicRot": 180.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt2", "useTex": true, "surfaceTexture": "ps4", "texScale": 1.49, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": true, "supportPressure": true, "pressReverse": true, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 100, "blendType": 0},
      {"id": "LYOhkGicSRW6Aw3vZpkY8Q", "name": "记号笔", "pkgName": "勾线画笔", "width": 19.6, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.7, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.06, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt15", "useTex": true, "surfaceTexture": "ps22", "texScale": 0.19999999, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 53, "blendType": 0},
      {"id": "JAHACJxYT0WbxozLueq8dA", "name": "针管笔", "pkgName": "勾线画笔", "width": 6.0, "smallWidth": 1.0, "dynamicWidth": 0.099999994, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 180.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt15", "useTex": true, "surfaceTexture": "ps15", "texScale": 0.19999999, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "QjdrJSAVQSWBT3p8Xtm9Xg", "name": "毡毛笔", "pkgName": "勾线画笔", "width": 90.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.59999996, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.049999997, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 354.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt2", "useTex": true, "surfaceTexture": "ps4", "texScale": 0.19999999, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 10, "blendType": 0},
      {"id": "uFcdhLL-Qr2L6tWiG104qg", "name": "手写笔", "pkgName": "勾线画笔", "width": 30.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.19999999, "dynamicBrushFlow": 0.0, "spacing": 0.049999997, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": true, "shapeTexture": "pt2", "useTex": false, "surfaceTexture": "", "texScale": 0.19999999, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 10, "blendType": 0},
      {"id": "Os1os6TeSDyEaybybaCcag", "name": "软木条", "pkgName": "勾线画笔", "width": 10, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt59", "useTex": true, "surfaceTexture": "ps10", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 10, "blendType": 0},
    ],
  },
  { name: "绘画肌理", brushes: [
      {"id": "HiGq6jY4Q6iBbbZn3BdgEw", "name": "硬蜡笔", "pkgName": "绘画肌理", "width": 200.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 1.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.19999999, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 183.0, "dynamicRot": 0.0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt4", "useTex": true, "surfaceTexture": "ps9", "texScale": 1.8, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.01999998, "hollowVal": 0.0, "depth": 15, "blendType": 0},
      {"id": "k8CFTC4TQp-ULi1r34Bsmg", "name": "油墨", "pkgName": "绘画肌理", "width": 200.0, "smallWidth": 90.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 1.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 108.0, "dynamicRot": 0.0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt6", "useTex": true, "surfaceTexture": "ps15", "texScale": 2.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": -0.100000024, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "_8BF7NufQ1qANvgdZU0kQQ", "name": "软蜡笔", "pkgName": "绘画肌理", "width": 180.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.59999996, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.099999994, "dynamicSpa": 0.0, "hardness": 0.39999998, "roundness": 1.0, "rotation": 183.0, "dynamicRot": 180.0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt2", "useTex": true, "surfaceTexture": "ps17", "texScale": 0.7, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.01999998, "hollowVal": 0.0, "depth": 30, "blendType": 0},
      {"id": "YsVTuJaiTS2-pPcK0hO09g", "name": "粗麻", "pkgName": "绘画肌理", "width": 130.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 1.0, "dynamicAlpha": 0.0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.06, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 183.0, "dynamicRot": 108.0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt4", "useTex": true, "surfaceTexture": "ps31", "texScale": 1.1, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.01999998, "hollowVal": 0.0, "depth": 8, "blendType": 0},
      {"id": "al8yM8dMRU68Me0a9tAKPQ", "name": "干刷", "pkgName": "绘画肌理", "width": 200.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.29999998, "smallBrushFlow": 0.0, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 0.81, "rotation": 157.0, "dynamicRot": 0.0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt7", "useTex": true, "surfaceTexture": "ps16", "texScale": 1.0, "reverseTex": false, "reverseShape": true, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0.0, "hollowVal": 0.0, "depth": 52, "blendType": 0},
      {"id": "3Rf8zv31Sr6jSc5Epwv4LQ", "name": "石墨", "pkgName": "绘画肌理", "width": 200.0, "smallWidth": 90.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.099999994, "dynamicAlpha": 0.0, "brushFlow": 0.59999996, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 87.0, "dynamicRot": 0.0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt4", "useTex": true, "surfaceTexture": "ps15", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": -0.100000024, "hollowVal": 0.0, "depth": 45, "blendType": 0},
      {"id": "Rc8Y5oE9S767pmHTV1dRXQ", "name": "潦草帆布", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.79999995, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.049999997, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 62, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt47", "useTex": true, "surfaceTexture": "ps34", "texScale": 2, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 3, "blendType": 0},
      {"id": "gcnAJhwVQuK-53OUl13IUw", "name": "瓦楞纸", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.79999995, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.049999997, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 62, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt57", "useTex": true, "surfaceTexture": "ps34", "texScale": 2, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 3, "blendType": 0},
      {"id": "OqwJ4L-2QGu61R0C4l1KBw", "name": "织布印染", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 90, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt41", "useTex": true, "surfaceTexture": "ps19", "texScale": 3, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 10, "blendType": 0},
      {"id": "cS48arEMSVWHFva7KZL88A", "name": "干水粉", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 194, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt43", "useTex": true, "surfaceTexture": "ps38", "texScale": 1.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 35, "blendType": 0},
      {"id": "8673BwKMQE-8hMeh8c5CoQ", "name": "肥皂", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.14999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt44", "useTex": true, "surfaceTexture": "ps22", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "4srZyy32QnytRQwvRvxFzg", "name": "面包屑", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt42", "useTex": true, "surfaceTexture": "ps10", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "-NPcyo4NStKju64U9rtsDg", "name": "海绵", "pkgName": "绘画肌理", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 140, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt55", "useTex": true, "surfaceTexture": "ps4", "texScale": 1, "reverseTex": true, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
    ],
  },
  { name: "基础画笔", brushes: [
      {"id": "lrQ1R2GwR-igtHM1r4ba3Q", "name": "压感柔边", "pkgName": "基础画笔", "width": 100.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.13, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.14999999, "dynamicSpa": 0.0, "hardness": 0.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "AyKEoE4KQryzsJ49iJL_lw", "name": "软画笔", "pkgName": "基础画笔", "width": 200.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.13, "dynamicAlpha": 0.0, "brushFlow": 0.099999994, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.19999999, "dynamicSpa": 0.0, "hardness": 0.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "L-1kQtNSSC2qcxd6qMQD0w", "name": "柔边圆笔", "pkgName": "基础画笔", "width": 200.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.13, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.19999999, "dynamicSpa": 0.0, "hardness": 0.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "z-HnyK6_RCa7X8lE2wATqw", "name": "压感软画笔", "pkgName": "基础画笔", "width": 200.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.13, "dynamicAlpha": 0.0, "brushFlow": 0.14999999, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.19999999, "dynamicSpa": 0.0, "hardness": 0.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "Ozck4QLUTi655tP-zUaDfA", "name": "压感硬边", "pkgName": "基础画笔", "width": 130.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.13, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.049999997, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "44gx1zmxQ3iXDMyxLFwcDA", "name": "硬边圆笔", "pkgName": "基础画笔", "width": 100.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.13, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.049999997, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "mE64UV8DSFarH8No5Ev0jQ", "name": "硬画笔", "pkgName": "基础画笔", "width": 100.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 1.0, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.02, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
      {"id": "NotUbVKhQwGIArtLlK_6iQ", "name": "流量硬画笔", "pkgName": "基础画笔", "width": 100.0, "smallWidth": 1.0, "dynamicWidth": 0.0, "minWidth": 1.0, "maxWidth": 500.0, "alpha": 1.0, "smallAlpha": 0.0, "dynamicAlpha": 0.0, "brushFlow": 0.049999997, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0.0, "spacing": 0.049999997, "dynamicSpa": 0.0, "hardness": 1.0, "roundness": 1.0, "rotation": 0.0, "dynamicRot": 0.0, "rotFlowFinger": false, "useShape": false, "shapeTexture": "", "useTex": false, "surfaceTexture": "", "texScale": 1.0, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": -1.0, "hollowVal": 0.0, "depth": 0, "blendType": 0},
    ],
  },
  { name: "喷枪", brushes: [
      {"id": "dR4B012WRqaq2fmEbHzHqw", "name": "涂鸦喷枪", "pkgName": "喷枪", "width": 50, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0, "dynamicAlpha": 0, "brushFlow": 0.7, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.07, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt58", "useTex": true, "surfaceTexture": "ps35", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 3, "blendType": 0},
      {"id": "eMnUA5imS528GpIf-zZ37A", "name": "细小颗粒", "pkgName": "喷枪", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.5, "dynamicAlpha": 0, "brushFlow": 0.29999998, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt21", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 30, "blendType": 0},
      {"id": "8vmZfm-nRrO86YAs_TdRYQ", "name": "中等颗粒", "pkgName": "喷枪", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt21", "useTex": false, "surfaceTexture": "", "texScale": 2, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 3, "blendType": 0},
      {"id": "Sn-R2sS-RFq77iHBOmWKkA", "name": "大颗粒", "pkgName": "喷枪", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt21", "useTex": false, "surfaceTexture": "", "texScale": 2, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 3, "blendType": 0},
      {"id": "5Z48MahnShuku0Px2zn2mA", "name": "飞溅", "pkgName": "喷枪", "width": 200, "smallWidth": 1, "dynamicWidth": 1, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.5, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.39999998, "dynamicSpa": 0.5, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt21", "useTex": false, "surfaceTexture": "", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 30, "blendType": 0},
      {"id": "cEKVRqP8SaCJ6xRYqYsvTg", "name": "白雪", "pkgName": "喷枪", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt61", "useTex": true, "surfaceTexture": "ps7", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "Yi-mxUVnTke5c-9qTH0E4A", "name": "沙盐", "pkgName": "喷枪", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.39999998, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt44", "useTex": true, "surfaceTexture": "ps43", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 16, "blendType": 0},
    ],
  },
  { name: "材质元素", brushes: [
      {"id": "CrZglSucRGKDr5iuIM4CXA", "name": "皮肤", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.29999998, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt51", "useTex": true, "surfaceTexture": "ps23", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 10, "blendType": 0},
      {"id": "UwohSB2qQcOVjDyBIbszHw", "name": "木板", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.099999994, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt48", "useTex": true, "surfaceTexture": "ps10", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "jEdQCEaaSteuv9vxiaydKg", "name": "皮革", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.19999999, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt52", "useTex": true, "surfaceTexture": "ps23", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 5, "blendType": 0},
      {"id": "ok_eK4b6Sguo_mebvmA-PA", "name": "青铜", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.19999999, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt53", "useTex": true, "surfaceTexture": "ps23", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 5, "blendType": 0},
      {"id": "iyJ8bNu1QiKJqF6gXBgh_g", "name": "龟裂", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.19999999, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt45", "useTex": true, "surfaceTexture": "ps10", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 10, "blendType": 0},
      {"id": "Iqid8bJeSZq20UFWkgXETA", "name": "石头墙", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.19999999, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt54", "useTex": true, "surfaceTexture": "ps10", "texScale": 1.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 5, "blendType": 0},
      {"id": "QqfCK87mTHub4pB3clr_hA", "name": "岩石壁", "pkgName": "材质元素", "width": 200, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.19999999, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt62", "useTex": true, "surfaceTexture": "ps10", "texScale": 1.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 5, "blendType": 0},
      {"id": "evOhaReGS_WNuDS8W9jUng", "name": "车辙印", "pkgName": "材质元素", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.17999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 90, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt50", "useTex": true, "surfaceTexture": "ps39", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": true, "supportPressure": false, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "uHxkC-awS06P5jqOxFiacA", "name": "铁丝网", "pkgName": "材质元素", "width": 60, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 0.5, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.099999994, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 26, "dynamicRot": 50, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt56", "useTex": true, "surfaceTexture": "ps10", "texScale": 0.3, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "ZncgHLIMTLKrYnA1i4NLcg", "name": "紫叶李", "pkgName": "材质元素", "width": 50, "smallWidth": 1, "dynamicWidth": 1, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0.02, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 180, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt60", "useTex": true, "surfaceTexture": "ps37", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 30, "blendType": 0},
      {"id": "Q4JDCRsLT8Sua4-Eus4cPg", "name": "碎木片", "pkgName": "材质元素", "width": 50, "smallWidth": 1, "dynamicWidth": 1, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 1, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.19999999, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": true, "shapeTexture": "pt23", "useTex": true, "surfaceTexture": "ps46", "texScale": 0.29999998, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": false, "smearStrength": 0, "hollowVal": 0, "depth": 30, "blendType": 0},
    ],
  },
  { name: "漫画网点", brushes: [
      {"id": "YoPpLuxCSUGbPgodlzv3xA", "name": "小方块", "pkgName": "漫画网点", "width": 325, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt65", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "IWYdCAVyTHmQBv0r4cJQng", "name": "波纹", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt66", "texScale": 0.79999995, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "q8aTLcclQomt_cvECf8kJQ", "name": "错位圆点", "pkgName": "漫画网点", "width": 500, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt63", "texScale": 0.049999997, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 0, "blendType": 0},
      {"id": "pgpIslfeSeaykStQ8P8y8g", "name": "方格", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt67", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "vcmrSb_jQ-aa-JzYL2nD1g", "name": "棋盘格", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt68", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "Y-8bifxPQE6lZ5UA4Xz6iQ", "name": "斜方格", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt69", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "lNnH-DPLR0maNMJONYsOIg", "name": "网点灰面", "pkgName": "漫画网点", "width": 68, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt70", "texScale": 0.099999994, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 50, "blendType": 0},
      {"id": "jPWCjg5RQMWMNPAf9OMecg", "name": "有序波点", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt71", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "ZNS0t17_SZerkNhjn_xfcQ", "name": "无序波点", "pkgName": "漫画网点", "width": 92, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt72", "texScale": 0.7, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "xCm_oLNiQ2iLgj-ItzlxXw", "name": "六边形", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt73", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "ItRxwPQkQr6bvrxoC37jRA", "name": "黑白条", "pkgName": "漫画网点", "width": 91, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt74", "texScale": 1, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": true, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
      {"id": "BmacloV6RMui4SIvk0FTpA", "name": "交叉网点", "pkgName": "漫画网点", "width": 100, "smallWidth": 1, "dynamicWidth": 0, "minWidth": 1, "maxWidth": 500, "alpha": 1, "smallAlpha": 0.13, "dynamicAlpha": 0, "brushFlow": 1, "smallBrushFlow": 0.13, "dynamicBrushFlow": 0, "spacing": 0.08, "dynamicSpa": 0, "hardness": 1, "roundness": 1, "rotation": 0, "dynamicRot": 0, "rotFlowFinger": true, "useShape": false, "shapeTexture": "", "useTex": true, "surfaceTexture": "pt75", "texScale": 0.5, "reverseTex": false, "reverseShape": false, "eraser": false, "pixelpen": false, "square": false, "supportPressure": false, "pressReverse": false, "rgbToAlpha": true, "smearStrength": 0, "hollowVal": 0, "depth": 100, "blendType": 0},
    ],
  },
];

export const ALL_BRUSHES: BrushPreset[] = PACKAGES.flatMap((p) => p.brushes);

/** name→id map for CLI/UI lookup by Chinese name. */
export const NAME_TO_ID: Record<string, string> = Object.fromEntries(
  ALL_BRUSHES.map((b) => [b.name, b.id]),
);

export function getById(id: string): BrushPreset {
  return ALL_BRUSHES.find((b) => b.id === id) ?? DEFAULT_BRUSH;
}

/** Lookup by Chinese name OR id. Falls back to DEFAULT_BRUSH. */
export function getByNameOrId(query: string): BrushPreset {
  // Try exact name match first
  const byName = ALL_BRUSHES.find((b) => b.name === query);
  if (byName) return byName;
  // Then try ID
  const byId = ALL_BRUSHES.find((b) => b.id === query);
  if (byId) return byId;
  // Then partial name match
  const partial = ALL_BRUSHES.find((b) => b.name.includes(query) || b.id.includes(query));
  return partial ?? DEFAULT_BRUSH;
}

export function findByName(query: string): BrushPreset[] {
  const q = query.toLowerCase();
  return ALL_BRUSHES.filter((b) => b.name.toLowerCase().includes(q) || b.id.toLowerCase().includes(q));
}

export function getDefault(): BrushPreset { return DEFAULT_BRUSH; }

export function getRequiredTextures(): Set<string> {
  const t = new Set<string>();
  for (const b of ALL_BRUSHES) {
    if (b.shapeTexture) t.add(b.shapeTexture);
    if (b.surfaceTexture) t.add(b.surfaceTexture);
  }
  return t;
}
